- store/blocks/minicart.jsonc
- styles/css/vtex.checkout-summary.css
- styles/css/vtex.flex-layout.css
- styles/css/vtex.minicart.css
- styles/css/vtex.product-list.css
> Vtex minicart UI update v1

- manifest.json
- store/blocks/home/home.jsonc
- store/blocks/pdp/product.jsonc
- styles/css/vtex.product-price.css
- styles/css/vtex.store-components.css
- styles/css/vtex.tab-layout.css
1. Product detail page changes ( includes Hero image, Product title, Price display, product details )
2. Create Tab structure for Details, Additional info and Reviews
> Following features are added for Vtex_Ech_Demo :

- styles/css/vtex.store-components.css
UI fix for search bar not coming with input field.
> search bar UI fix

- styles/css/vtex.my-account.css
Updated my accounts page with styling.
> Account Page

- store/blocks/header/header.jsonc
- store/blocks/search.jsonc
- styles/css/search/vtex.search.css
- styles/css/vtex.flex-layout.css
- styles/css/vtex.search-result.css
- styles/css/vtex.store-components.css
> Search bar mobile

- store/blocks/footer/footer.json
- store/blocks/footer/menu.json
- store/blocks/home/home.jsonc
- store/blocks/pdp/product.jsonc
- styles/css/vtex.flex-layout.css
- styles/css/vtex.menu.css
- styles/css/vtex.rich-text.css
- styles/css/vtex.store-components.css
- styles/css/vtex.store-footer.css
new branch created with responsive layout
> new branch created with responsive layout

- store/blocks/pdp/product.jsonc
- styles/css/vtex.disclosure-layout.css
- styles/css/vtex.store-icons.css
PDP Page tab-layout converted to accordion-style for mobile view.
> PDP Page tab-layout converted to accordion style for mobile view.

- store/blocks/corporate-blog.jsonc
- store/blocks/footer/footer.json
- store/blocks/footer/menu.json
- store/blocks/store-features.jsonc
- store/blocks/upcoming-features.jsonc
- styles/css/vtex.store-components.css
1.contents added for corporate blog, store and upcoming features.
2. newsletter button alignment corrected.
3. My profile and My order links are updated in footer.
4. payment methods are coming with color now.
5. Pinterest icon is added to social network icons in footer.
> contents added for custom pages

- react/Conflicts/url.js
- react/components/Major Appliances/index.js
- react/components/Small Appliances/index.js
- react/utills/httpCall.js
Created makeAPICall function in httpCall.js file for all API fetch request. This function api can be used in all the module for all type of fetch API request.
> Created makeAPICall function in httpCall.js file for all API fetch request.

- react/components/Major Appliances/index.js
- react/components/Small Appliances/index.js
Added statics images and css to Majorappliances and Smallappliances.
> Added statics images and css to Majorappliances and Smallappliances.

- manifest.json
- react/Config/url.js
- react/ContactFormDataWrapper.js
- react/ContactUsDataWrapper.js
- react/ContactUsHistory.js
- react/components/ContactFormData/ContactFormData.css
- react/components/ContactFormData/index.js
- react/components/ContactUsData/ContactUsData.css
- react/components/ContactUsData/index.js
- store/blocks/contact-us.jsonc
- store/blocks/contactForm-data.jsonc
- store/interfaces.json
- store/routes.json
- styles/css/vtex.flex-layout.css
Created new page to display contact-us form history and displays the contact details of the current user.
> Created new page to display contact-us form history

- react/components/WomenMenuItems/WomenMenu.css
- react/components/WomenMenuItems/index.js
- store/blocks/header/header.jsonc
Fix:
1.Added responsiveness for megaMenu
2.Added accordion to mobile view
> Added responsiveness for mega menu

- react/CategoryMenu.css
- react/Config/url.js
- react/ElectronicsMenu.js
- react/MajorAppMenu.js
- react/SmallAppMenu.js
- react/components/ElectronicsMenuItems/index.js
- react/components/MajorAppMenuItems/index.js
- react/components/SmallAppMenuItems/index.js
- react/components/WomenMenuItems/index.js
- store/blocks/header/category-menu.json
- store/blocks/header/header.jsonc
- store/blocks/header/main-menu.json
- store/interfaces.json
Fix:
1.Made the Menu Items dynamic.
2.Created departments as main menu and fetched the subcategories under each department.
> Created dynamic MenuItems

- react/Config/url.js
- react/components/WomenMenuItems/index.js
- store/blocks/header/main-menu.json
> Included links to Main menu

- store/blocks/product-summary/product-summary.jsonc
- store/blocks/product-summary/quickview.json
Included Reviews and Ratings to home page, pdp page, plp page and quick view modal.
> Included Reviews and Ratings 

- store/blocks/header/category-menu.json
- store/blocks/pdp/product.jsonc
- styles/css/search/vtex.flex-layout.css
- styles/css/vtex.add-to-cart-button.css
Fix:
1.Added responsiveness for buy-wish-button 
2.Added responsiveness for My Account
> Added responsiveness for buy-wish-button and My Account

- manifest.json
- react/components/Electronics/index.js
- react/components/MyAccountTab/Myaccount.css
- store/blocks/footer/footer.json
- store/blocks/footer/menu.json
- store/blocks/header/header.jsonc
- store/blocks/header/main-menu-static.json
- store/blocks/home/home.jsonc
- styles/css/vtex.disclosure-layout.css
- styles/css/vtex.login.css
- styles/css/vtex.menu.css
- styles/css/vtex.minicart.css
Added accordion in mobile view to footer and header, fixed CSS issues in login page and main-header, linked social icons.
> Added accordion in mobile view to footer, header & fixed CSS issues.

- store/blocks/home/home.jsonc
- styles/css/vtex.store-components.css
1.sku alignments is done as per the requirement
2. Newsletter confirmation message color changed
3. view all button is now redirecting to sales page
> sku alignments and newsletter confirmation msg color

- react/components/ContactFormData/ContactFormData.css
- react/components/ContactFormData/index.js
- store/blocks/contact-us.jsonc
- styles/css/vtex.login.css
- styles/css/vtex.rich-text.css
Fixed styling for Contact Us History page , Contact Us form & login page
> Fixed styling for Contact Us History page, Contact Us form & login page

- styles/css/vtex.store-components.css
1. Commented center alignments of sku selectors.
> Some css for sku alignments are commented

- store/blocks/pdp/product.jsonc
- store/blocks/terms-use.jsonc
- styles/css/vtex.rich-text.css
- styles/css/vtex.store-icons.css
PDP page accordian and "Term of use" page updated.
> PDP page accordian and "Term of use" page updated.

- react/components/Electronics/Electronics.css
- store/blocks/footer/footer.json
- store/blocks/home/home.jsonc
- styles/css/custom-template-blackfriday-lp/vtex.flex-layout.css
- styles/css/custom-template-blackfriday-lp/vtex.store-components.css
- styles/css/vtex.flex-layout.css
- styles/css/vtex.search-result.css
- styles/css/vtex.store-footer.css
1.Social networks alignment in mobile screen is corrected.
2.news letter alignment for large screen is solved.
3. alignments of custom icons in career page for mobile screen.
4. department page images for mobile screen is corrected.
5. sales page images for mobile screen is corrected.
6. sort by relevance dropdown z-index issue in plp solved.
> checked responsiveness

- styles/css/custom-template-blackfriday-lp/vtex.flex-layout.css
- styles/css/custom-template-blackfriday-lp/vtex.store-components.css
- styles/css/vtex.search-result.css
- styles/css/vtex.store-components.css
1) made following pages responsive for landscape mobile and tablet views
1)Home page
2)PLP
3)all department pages (CLP)
5)all pages under about us section in footer.
6) sales page
> responsiveness for landscape view

- react/components/ContactFormData/ContactFormData.css
- react/components/ContactFormData/Hooks/useTable.js
- react/components/ContactFormData/Table/Table.css
- react/components/ContactFormData/Table/Table.js
- react/components/ContactFormData/Table/TableFooter/TableFooter.css
- react/components/ContactFormData/Table/TableFooter/TableFooter.js
- react/components/ContactFormData/index.js
Included Pagination to Contact Us History page
> Included Pagination to Contact Us History page

- store/blocks/custom-template-blackfriday-lp/custom-template-blackfriday-lp.jsonc
- styles/css/custom-template-blackfriday-lp/vtex.flex-layout.css
- styles/css/custom-template-blackfriday-lp/vtex.store-components.css
Some global css were there in Sales page, and they were breaking pdp page in landscape view. Removed them and added new css with block class.
> some global css in sale page removed and added new css classes

- manifest.json
- store/blocks/custom-template-blackfriday-lp/custom-template-blackfriday-lp.jsonc
- store/blocks/home/home.jsonc
- store/blocks/pdp/product.jsonc
- store/blocks/product-comparison.json
- store/blocks/product-summary/product-summary-list.jsonc
- store/blocks/product-summary/product-summary.jsonc
- store/blocks/search.jsonc
- store/interfaces.json
- store/routes.json
- styles/css/vtex.product-comparison.css
- styles/css/vtex.product-summary.css
- styles/css/vtex.reviews-and-ratings.css
- styles/css/vtex.search-result.css
- styles/css/vtex.slider-layout.css
Added product compare checkbox in PLP and PDP
> Added product compare option

- react/Utils/httpCall.js
- react/components/ContactFormData/index.js
Added Request Range to Contact Us form History
> Added Request Range to Contact Us form History

- styles/css/search/vtex.flex-layout.css
Fix:
1.Fixed alignment issues for SKU List
> Fixed alignment issues for SKU List

- styles/css/custom-template-blackfriday-lp/vtex.flex-layout.css
- styles/css/faq/vtex.disclosure-layout.css
- styles/css/vtex.wish-list.css
Landscape view updated for
1. shipping policy page,
2. pdp page
> Landscape view updated for 1. shipping policy page, 2. pdp page

- react/components/ContactFormData/ContactFormData.css
- react/components/ContactFormData/Table/Table.css
- react/components/ContactFormData/Table/TableFooter/TableFooter.css
- react/components/UserSupportPage/UserSupportPage.css
- react/components/UserSupportPage/index.js
- styles/css/vtex.my-account.css
Added back button to user support page,
Made My account Addresses section and User Support responsive
Improved styling of Contact us history page to make responsive
> Fixed styling and issues

- react/Config/url.js
- react/SellersSite.js
- react/components/SellersSite/index.js
- store/blocks/pdp/product.jsonc
- store/blocks/pdp/sellers.jsonc
- store/blocks/product-summary/product-summary.jsonc
- store/interfaces.json
1)Added seller selector custom block, which will redirects to seller sites.
2)Added product summary sku selector block. As of now just commented those block code.
3)Added navigation arrows and pagination dots for pdp image
> seller selector custom block and sku changes
